[build]
  # 构建命令 - 安装依赖但不构建
  command = "npm install"

  # 发布目录 - 整个项目根目录作为静态站点
  publish = "."

  # 忽略构建条件 - 当没有变化时跳过构建
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18"

# 重定向规则 - 处理单页应用路由
[[redirects]]
  # 默认首页重定向到 cesium-stable.html
  from = "/"
  to = "/cesium-stable.html"
  status = 200

[[redirects]]
  # 处理原型页面路由
  from = "/prototype/*"
  to = "/原型页面/:splat"
  status = 200

[[redirects]]
  # 处理 PC 端页面路由
  from = "/pc/*"
  to = "/原型页面/pc端/:splat"
  status = 200

[[redirects]]
  # 处理监控仪表板
  from = "/dashboard"
  to = "/原型页面/pc端/pages/monitor/dashboard.html"
  status = 200

[[redirects]]
  # 处理地灾监控大屏
  from = "/geological-dashboard"
  to = "/原型页面/pc端/pages/monitor/geological-disaster-dashboard.html"
  status = 200

# 头部设置 - 解决 CORS 问题
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 针对 CesiumJS 资源的特殊头部
[[headers]]
  for = "/node_modules/cesium/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

# 针对静态资源的缓存设置
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# 处理 HTML 文件
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "text/html; charset=utf-8"

# 错误页面处理
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# 函数配置（如果需要）
[functions]
  directory = "netlify/functions"
